### PR TITLE
chore(action): Update actions/core and actions/github dependencies

### PR DESCRIPTION
**Pull request by rajivshah3**
## Motivation

Updates [`@actions/core`](https://github.com/actions/toolkit/tree/main/packages/core) to 1.10.0 and [`@actions/github`](https://github.com/actions/toolkit/tree/main/packages/github) to 5.1.1. The `@actions/core` update resolves [deprecation warnings](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) coming from calls to `core.setOutput()`, which will be removed in June 2023.

## Approach

Updates dependencies

### Possible Drawbacks or Risks

N/A

### TODOs and Open Questions

- [ ] Rebuild the action dist (I can do this if you prefer)

### CODE REVIEW

**Comment by jbolda** [comment]
Cheers! This action `dist` update should be handled by the workflows. Please update the related `package.json` versions to suit and add a change file, then it should be good to go.

**Review by jbolda — CHANGES_REQUESTED** [review]
Cheers! This action `dist` update should be handled by the workflows. Please update the related `package.json` versions to suit and add a change file, then it should be good to go.

**Review by jbolda — APPROVED** [review]
Were pretty minor changes so just went ahead and pushed them. Thanks again!

**Comment by rajivshah3** [comment]
Sorry for not responding @jbolda ! Was busy with exams last week. Thanks for merging!

**Pull request merged**
